@baseUrl = http://127.0.0.1:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5MTkzNDgyMC05MDE4LTQyNDgtODAyZC02OTAyODg0YWYwZWIiLCJyb2wiOiJBRE1JTiIsInNlZGVJZCI6InNlZWQtYm9kZWdhLWNlbnRyYWwiLCJlbXByZXNhSWQiOiJiODkyNTJmZC05MTZkLTQ2MDgtYmFmMC1iMmJlOWYzYjQzZTIiLCJpYXQiOjE3ODgyMjMyODYsImV4cCI6MTc4ODI1MjA4Nn0.jLLzR3E9uqmGSS2HtazPp1O94pCZiMfb2bHe6TRl1c0

### Ver unidades de medida
GET {{baseUrl}}/unidades-medida
Authorization: Bearer {{token}}

### Crear una Sede (Cafetería Valledupar)
POST {{baseUrl}}/sedes
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nombre": "Cafetería Valledupar",
  "tipo": "CAFETERIA",
  "ciudad": "Valledupar"
}

### Ver todas las sedes
GET {{baseUrl}}/sedes
Authorization: Bearer {{token}}

### Crear un Tercero (cliente persona natural, sin NIT)
POST {{baseUrl}}/terceros
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "tipoPersona": "NATURAL",
  "tipoDocumento": "CC",
  "numeroDocumento": "1065600123",
  "nombreCompleto": "Cliente de Prueba"

}

### Crear un Tercero (proveedor jurídico, con NIT - probamos el cálculo de DV)
POST {{baseUrl}}/terceros
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "tipoPersona": "JURIDICA",
  "tipoDocumento": "NIT",
  "numeroDocumento": "900123456",
  "nombreCompleto": "Distribuidora de Insumos S.A.S.",
  "esCliente": false,
  "esProveedor": true
}

### Ver todos los terceros
GET {{baseUrl}}/terceros
Authorization: Bearer {{token}}

### Crear un Producto vendible (Dona de Chocolate)
POST {{baseUrl}}/productos
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "codigo": "PROD-001",
  "nombre": "Dona de Chocolate",
  "tipo": "VENDIBLE_PROPIO",
  "unidadMedidaId": "cb674d5a-9979-4d19-b5dc-96d8273ca886",
  "precioVenta": 4500,
  "aplicaInc": true
}

### Crear un Producto insumo (Harina)
POST {{baseUrl}}/productos
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "codigo": "INS-001",
  "nombre": "Harina de Trigo",
  "tipo": "INSUMO",
  "unidadMedidaId": "795ed845-4218-4f0f-b73a-334f5076592b"
}

### Ver todos los productos
GET {{baseUrl}}/productos
Authorization: Bearer {{token}}git add .
git status